FROM golang:alpine AS application

FROM golang:alpine AS builder
RUN apk add --no-cache --update gcc g++

WORKDIR /fake_server
COPY fake_web fake_web

WORKDIR /fake_server/fake_web
RUN go mod tidy
RUN CGO_ENABLED=1 go build

FROM application
WORKDIR /app

RUN CGO_ENABLED=1

COPY --from=builder /fake_server/fake_web/fake_web /app
COPY --from=builder /fake_server/fake_web/render_html /app/render_html
COPY --from=builder /fake_server/fake_web/cert /app/cert

CMD [ "/app/fake_web" ]